# Archivo de servicio de redis en Kubernetes, conexion con la bd

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis
