-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."PSUsers"
(
    "IdUser" integer NOT NULL,
    "firstName" character varying(30) NOT NULL,
    "lastName" character varying(30) NOT NULL,
    "passwordHash" bytea NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "lastLogin" timestamp without time zone NOT NULL,
    checksum bytea NOT NULL,
    "IdUserStatus" integer NOT NULL,
    PRIMARY KEY ("IdUser")
);

CREATE TABLE IF NOT EXISTS public."PSUserStatus"
(
    "IdUserStatus" integer NOT NULL,
    name character varying(20) NOT NULL,
    PRIMARY KEY ("IdUserStatus")
);

CREATE TABLE IF NOT EXISTS public."PSCountries"
(
    "IdCountry" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("IdCountry")
);

CREATE TABLE IF NOT EXISTS public."PSStates"
(
    "IdState" integer NOT NULL,
    name character varying(30) NOT NULL,
    "IdCountry" integer NOT NULL,
    PRIMARY KEY ("IdState")
);

CREATE TABLE IF NOT EXISTS public."PSCities"
(
    "IdCIty" integer NOT NULL,
    name character varying(30) NOT NULL,
    "IdState" integer NOT NULL,
    PRIMARY KEY ("IdCIty")
);

CREATE TABLE IF NOT EXISTS public."PSAddresses"
(
    "IdAddress" integer NOT NULL,
    line1 character varying(200) NOT NULL,
    line2 character varying(200),
    zipcode character varying(10) NOT NULL,
    geolocation point NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "IdCity" integer NOT NULL,
    PRIMARY KEY ("IdAddress")
);

CREATE TABLE IF NOT EXISTS public."PSUserContactInfo"
(
    "IdUserContactInfo" integer NOT NULL,
    contact character varying(120) NOT NULL,
    enable bit NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "IdUser" integer NOT NULL,
    "IdContactInfoType" integer NOT NULL,
    PRIMARY KEY ("IdUserContactInfo")
);

CREATE TABLE IF NOT EXISTS public."PSContactInfoType"
(
    "IdContactInfoType" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("IdContactInfoType")
);

CREATE TABLE IF NOT EXISTS public."PSRoles"
(
    "IdRole" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdRole")
);

CREATE TABLE IF NOT EXISTS public."PSPermissions"
(
    "IdPermission" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("IdPermission")
);

CREATE TABLE IF NOT EXISTS public."PSPermissionsPerRole"
(
    "IdRole" integer NOT NULL,
    "IdPermission" integer NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public."PSRolesPerUser"
(
    "IdUser" integer NOT NULL,
    "IdRole" integer NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    enabled bit NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public."PSLogTypes"
(
    "IdLogType" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("IdLogType")
);

CREATE TABLE IF NOT EXISTS public."PSLogLevels"
(
    "IdLogLevel" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("IdLogLevel")
);

CREATE TABLE IF NOT EXISTS public."PSLogSources"
(
    "IdLogSource" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("IdLogSource")
);

CREATE TABLE IF NOT EXISTS public."PSLogs"
(
    "IdLog" integer NOT NULL,
    description character varying(500) NOT NULL,
    computer character varying(100) NOT NULL,
    username character varying(50) NOT NULL,
    "IdRef1" bigint,
    "IdRef2" bigint,
    value1 character varying(200),
    value2 character varying(200),
    checksum bytea NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "IdLogType" integer NOT NULL,
    "IdLogLevel" integer NOT NULL,
    "IdLogSource" integer NOT NULL,
    PRIMARY KEY ("IdLog", "IdLogType", "IdLogLevel", "IdLogSource")
);

CREATE TABLE IF NOT EXISTS public."PSOrganizations"
(
    "IdOrganization" integer NOT NULL,
    name character varying(40) NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "cedulaJuridica" character varying(30) NOT NULL,
    "sociedadAnonima" character varying(40) NOT NULL,
    "addressNoFiscal" character varying(40) NOT NULL,
    PRIMARY KEY ("IdOrganization")
);

CREATE TABLE IF NOT EXISTS public."PSUsersXOrganization"
(
    "IdOrganization" integer NOT NULL,
    "IdUser" integer NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    enabled bit NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public."PSCurrencies"
(
    "IdCurrency" smallint NOT NULL,
    name character varying(30) NOT NULL,
    "isoCode" character varying(3) NOT NULL,
    "currencySymbol" character varying(5) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "IdCountry" integer NOT NULL,
    UNIQUE ("IdCountry")
);

CREATE TABLE IF NOT EXISTS public."PSExchangeRates"
(
    "IdExchangeRate" integer NOT NULL,
    "startDate" date NOT NULL,
    "endDate" date,
    "exchangeRate" numeric(10, 4) NOT NULL,
    "IdCurrencyDestiny" integer NOT NULL,
    "IdCurrencySource" integer NOT NULL,
    current bit(1) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdExchangeRate")
);

CREATE TABLE IF NOT EXISTS public."PSPaymentStatus"
(
    "IdPaymentStatus" integer NOT NULL,
    name character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdPaymentStatus")
);

CREATE TABLE IF NOT EXISTS public."PSPaymentTypes"
(
    "IdPaymentType" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(200) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdPaymentType")
);

CREATE TABLE IF NOT EXISTS public."PSPaymentMethods"
(
    "IdPaymentMethod" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(150) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdPaymentMethod")
);

CREATE TABLE IF NOT EXISTS public."PSPayments"
(
    "IdPayment" bigint NOT NULL,
    "transactionAmount" numeric(16, 2) NOT NULL,
    "IdCurrency" integer NOT NULL,
    description character varying(200),
    "paymentDate" timestamp without time zone NOT NULL,
    "IdPaymentType" integer NOT NULL,
    "IdPaymentStatus" integer NOT NULL,
    "IdPaymentMethod" integer NOT NULL,
    checksum bytea NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "IdUser" integer NOT NULL,
    PRIMARY KEY ("IdPayment", "IdPaymentType", "IdPaymentStatus", "IdPaymentMethod")
);

CREATE TABLE IF NOT EXISTS public."PSFeatures"
(
    "IdFeature" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(150) NOT NULL,
    "dataType" character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "featurePrice" numeric(10, 2),
    PRIMARY KEY ("IdFeature")
);

CREATE TABLE IF NOT EXISTS public."PSSubscriptions"
(
    "IdSubscription" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(200) NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL,
    "subAmount" numeric(15, 2) NOT NULL,
    "IdCurrencyType" integer NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdSubscription")
);

CREATE TABLE IF NOT EXISTS public."PSFeaturesPerSuscription"
(
    "IdSubscription" integer NOT NULL,
    "IdFeature" integer NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public."PSSubscriptionsPerUser"
(
    "IdSubscription" integer NOT NULL,
    "IdUser" integer NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public."PSCampaigns"
(
    "IdCampaign" integer NOT NULL,
    "IdOrganization" integer NOT NULL,
    "campaignName" character varying(40) NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone NOT NULL,
    "IdCampaignStatus" integer NOT NULL DEFAULT 1,
    "totalBudget" numeric(12, 2) NOT NULL,
    "totalSpent" numeric(12, 2) NOT NULL,
    "totalRevenue" numeric(12, 2) NOT NULL,
    "ROI" numeric(10, 4) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "lastETLupdate" timestamp without time zone NOT NULL,
    "sourceServiceId" integer NOT NULL,
    "sourceServiceName" integer NOT NULL,
    "IdCurrency" integer NOT NULL,
    "IdService" integer NOT NULL,
    "IdControl" integer NOT NULL,
    PRIMARY KEY ("IdCampaign", "IdCampaignStatus")
);

CREATE TABLE IF NOT EXISTS public."PSCampaignMetrics"
(
    "IdCampaignMetric" integer NOT NULL,
    "IdCampaign" integer NOT NULL,
    "metricDate" timestamp without time zone NOT NULL,
    "totalReach" bigint,
    "totalImpressions" bigint,
    "totalClicks" bigint,
    "totalViews" bigint,
    "totalLikes" bigint,
    "totalShares" bigint,
    "totalComments" bigint,
    "totalReactions" bigint,
    "totalLeads" integer NOT NULL,
    "qualifiedLeads" integer,
    "totalConversions" integer,
    "conversionRate" numeric(5, 4),
    "dailySpent" numeric(12, 2),
    "dailyRevenue" numeric(12, 2),
    "costPerLead" numeric(12, 2),
    "costPerConversion" numeric(12, 2),
    "averageOrderValue" numeric(12, 2),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "dataSource" character varying(40) NOT NULL,
    PRIMARY KEY ("IdCampaignMetric")
);

CREATE TABLE IF NOT EXISTS public."PSCampaignChannels"
(
    "IdChannelSummary" integer NOT NULL,
    "IdCampaign" integer NOT NULL,
    "channelName" character varying(40) NOT NULL,
    "channelType" character varying(40) NOT NULL,
    "totalSpent" numeric(12, 2) NOT NULL,
    "totalRevenue" numeric(12, 2) NOT NULL,
    leads integer NOT NULL,
    conversions integer NOT NULL,
    impressions bigint NOT NULL,
    clicks bigint NOT NULL,
    "channelROI" numeric(10, 4) NOT NULL,
    "conversionRate" numeric(5, 4) NOT NULL,
    "clickRate" numeric(5, 4) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdChannelSummary")
);

CREATE TABLE IF NOT EXISTS public."PSCampaingMarkets"
(
    "IdCampaignMarket" integer NOT NULL,
    "IdCampaign" integer NOT NULL,
    "IdCountry" integer NOT NULL,
    "IdState" integer,
    "IdCity" bigint,
    "totalReach" bigint NOT NULL,
    conversions integer NOT NULL,
    "totalRevenue" numeric(12, 2) NOT NULL,
    leads integer NOT NULL,
    spent integer NOT NULL,
    "marketROI" numeric(10, 4) NOT NULL,
    "conversionRate" numeric(5, 4) NOT NULL,
    "averageOrderValie" numeric(10, 2) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdCampaignMarket")
);

CREATE TABLE IF NOT EXISTS public."PSLeadsSumarry"
(
    "IdLeadSumarry" integer NOT NULL,
    "IdCampaign" integer NOT NULL,
    "sumarryDate" timestamp without time zone NOT NULL,
    "totalLeads" integer NOT NULL,
    "currentLeads" integer NOT NULL,
    "qualifiedLeads" integer NOT NULL,
    "convertedLeads" integer NOT NULL,
    "rejectedLeads" integer NOT NULL,
    "qualificationRate" numeric(5, 4) NOT NULL,
    "conversionRate" numeric(5, 4) NOT NULL,
    "leadChannels" character varying(200),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdLeadSumarry")
);

CREATE TABLE IF NOT EXISTS public."PSSalesSumarry"
(
    "IdSaleSumarry" integer NOT NULL,
    "IdCampaign" integer NOT NULL,
    "saleDate" timestamp without time zone NOT NULL,
    "totalSales" integer NOT NULL,
    "totalRevenue" numeric(12, 2) NOT NULL,
    "averageOrderValue" numeric(10, 2) NOT NULL,
    "IdCurrency" integer NOT NULL,
    "productCategory" character varying(40) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdSaleSumarry")
);

CREATE TABLE IF NOT EXISTS public."PSContentUsage"
(
    "IdContentUsage" bigint NOT NULL,
    "IdCampaign" integer NOT NULL,
    "contentId" character varying(200) NOT NULL,
    "contentType" character varying(30) NOT NULL,
    "contentTitle" character varying(200) NOT NULL,
    "usageCount" integer NOT NULL,
    "totalViews" integer NOT NULL,
    "totalLikes" integer NOT NULL,
    "totalShares" integer NOT NULL,
    "totalComments" integer NOT NULL,
    "engamentRate" numeric(5, 4) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdContentUsage")
);

CREATE TABLE IF NOT EXISTS public."PSCampaignStatus"
(
    "IdCampaignStatus" integer NOT NULL,
    "statusName" character varying(30) NOT NULL,
    description character varying(200) NOT NULL,
    "isActive" bit NOT NULL DEFAULT 1,
    PRIMARY KEY ("IdCampaignStatus")
);

CREATE TABLE IF NOT EXISTS public."PSETLSources"
(
    "IdSource" integer NOT NULL,
    "sourceName" integer NOT NULL,
    "IdSourceType" integer NOT NULL,
    description character varying(150) NOT NULL,
    "connectionString" text NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    priority smallint NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdSource", "IdSourceType")
);

CREATE TABLE IF NOT EXISTS public."PSETLControl"
(
    "IdControl" integer NOT NULL,
    "IdSource" integer NOT NULL,
    "runStartTime" timestamp without time zone NOT NULL,
    "runEndTime" timestamp without time zone NOT NULL,
    status character varying(40) NOT NULL,
    "recordsProccessed" bigint NOT NULL,
    "recordsInserted" bigint NOT NULL,
    "recordsUpdated" bigint NOT NULL,
    "recordsFailed" bigint NOT NULL,
    "lastProccessedID" bigint NOT NULL,
    "executionTime" timestamp without time zone NOT NULL,
    "averageRecordTime" numeric(10, 4) NOT NULL,
    "detailsMessage" text,
    "executedBy" character varying(20) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "IdServiceConnection" integer NOT NULL,
    PRIMARY KEY ("IdControl")
);

CREATE TABLE IF NOT EXISTS public."PSETLErrors"
(
    "IdError" integer NOT NULL,
    "IdControl" integer NOT NULL,
    "errorTime" timestamp without time zone NOT NULL,
    "errorType" character varying(30) NOT NULL,
    "errorSeverity" character varying(30) NOT NULL,
    "errorMessage" text NOT NULL,
    "errorCode" character varying(20) NOT NULL,
    "sourceTable" character varying(100) NOT NULL,
    "sourceRecordId" character varying(100) NOT NULL,
    "failedOperation" character varying(20) NOT NULL,
    "errorData" character varying(200) NOT NULL,
    "isResolved" bit NOT NULL DEFAULT 0,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdError")
);

CREATE TABLE IF NOT EXISTS public."PSETLDataSync"
(
    "IdDataSync" integer NOT NULL,
    "IdSource" integer NOT NULL,
    "sourceTable" character varying(100) NOT NULL,
    "targetTable" character varying(100) NOT NULL,
    "lastSync" timestamp without time zone NOT NULL,
    "lastSyncId" bigint NOT NULL,
    "totalRecords" bigint NOT NULL,
    "lastSyncDuration" timestamp without time zone NOT NULL,
    "lastSuccesfulSync" timestamp without time zone NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdDataSync")
);

CREATE TABLE IF NOT EXISTS public."PSETLSourceTypes"
(
    "IdSourceType" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(200) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdSourceType")
);

CREATE TABLE IF NOT EXISTS public."PSAuthMethods"
(
    "IdAuthMethod" integer NOT NULL,
    "methodName" character varying(30) NOT NULL,
    description character varying(200) NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdAuthMethod")
);

CREATE TABLE IF NOT EXISTS public."PSAPISetups"
(
    "IdAPISetup" integer NOT NULL,
    "apiName" character varying(100) NOT NULL,
    "apiProvider" character varying(100) NOT NULL,
    "apiVersion" character varying(20) NOT NULL,
    "baseURL" character varying(255) NOT NULL,
    "IdAuthMethod" integer NOT NULL,
    "apiKey" bytea NOT NULL,
    "clientId" bytea NOT NULL,
    "clientSecret" bytea NOT NULL,
    "accessToken" bytea NOT NULL,
    "tokenExpiresAt" timestamp without time zone NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "lastUsed" timestamp without time zone NOT NULL,
    "lastTestResult" character varying(20) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdAPISetup")
);

CREATE TABLE IF NOT EXISTS public."PSMCPServers"
(
    "IdMCPServer" integer NOT NULL,
    "serverName" character varying(100) NOT NULL,
    "serverType" character varying(50) NOT NULL,
    description character varying(300) NOT NULL,
    "serverURL" character varying(255) NOT NULL,
    "serverPort" integer NOT NULL,
    protocol character varying(10) NOT NULL,
    "IdAuthMethod" integer NOT NULL,
    "authToken" bytea NOT NULL,
    "availableTools" character varying(300) NOT NULL,
    "isActive" bit NOT NULL DEFAULT 1,
    "responseTime" timestamp without time zone NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdMCPServer")
);

CREATE TABLE IF NOT EXISTS public."PSAPICallLogs"
(
    "IdAPICallLog" integer NOT NULL,
    "IdAPISetup" integer NOT NULL,
    "requestTimestamp" timestamp without time zone NOT NULL,
    "endPoint" character varying(200) NOT NULL,
    "httpMethod" character varying(10) NOT NULL,
    "requestHeaders" jsonb NOT NULL,
    "requestBody" jsonb NOT NULL,
    "requestSize" integer NOT NULL,
    "responseTimestamp" timestamp without time zone NOT NULL,
    statuscode integer NOT NULL,
    "responseHeaders" jsonb NOT NULL,
    "responseBody" jsonb NOT NULL,
    "responseSize" integer NOT NULL,
    "requestTimeMs" timestamp without time zone NOT NULL,
    "responseTimeMs" timestamp without time zone NOT NULL,
    "isSuccess" boolean NOT NULL,
    "errorMessage" text NOT NULL,
    "errorCode" character varying NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "IdControl" integer NOT NULL,
    PRIMARY KEY ("IdAPICallLog")
);

CREATE TABLE IF NOT EXISTS public."PSMCPRequestLogs"
(
    "IdMCPRequestLog" integer NOT NULL,
    "IdMCPServer" integer NOT NULL,
    "requestTimeStamp" timestamp without time zone NOT NULL,
    "toolName" character varying(100) NOT NULL,
    "toolInput" jsonb NOT NULL,
    "responseTimestamp" timestamp without time zone NOT NULL,
    "responseTimeMs" timestamp without time zone NOT NULL,
    "isSuccess" boolean NOT NULL,
    "errorMesagge" text NOT NULL,
    "errorType" character varying(50) NOT NULL,
    "tokenUsage" integer NOT NULL,
    "costEstimate" numeric(10, 6) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "IdControl" integer NOT NULL,
    PRIMARY KEY ("IdMCPRequestLog")
);

CREATE TABLE IF NOT EXISTS public."PSServices"
(
    "IdService" integer NOT NULL,
    "serviceName" character varying(40) NOT NULL,
    "IdServiceType" integer NOT NULL,
    description character varying(200) NOT NULL,
    "databaseType" character varying(20) NOT NULL,
    "primaryURL" character varying(255) NOT NULL,
    enabled bit NOT NULL DEFAULT 1,
    "currentVersion" character varying(20) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdService")
);

CREATE TABLE IF NOT EXISTS public."PSServiceConnections"
(
    "IdServiceConnection" integer NOT NULL,
    "IdSourceService" integer NOT NULL,
    "IdTargetService" integer NOT NULL,
    "connectionType" character varying(40) NOT NULL,
    "IdAPISetup" integer,
    "IdMCPServer" integer,
    enabled integer NOT NULL DEFAULT 1,
    "lastConnection" timestamp without time zone NOT NULL,
    "lastConnectionResult" character varying(40) NOT NULL,
    "totalRequests" bigint NOT NULL,
    "succesfulRequets" bigint NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdServiceConnection")
);

CREATE TABLE IF NOT EXISTS public."PSServiceTypes"
(
    "IdServiceType" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(150) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("IdServiceType")
);

ALTER TABLE IF EXISTS public."PSUsers"
    ADD FOREIGN KEY ("IDUserStatus")
    REFERENCES public."PSUserStatus" ("IdUserStatus") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSStates"
    ADD FOREIGN KEY ("IDCountry")
    REFERENCES public."PSCountries" ("IdCountry") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCities"
    ADD FOREIGN KEY ("IDState")
    REFERENCES public."PSStates" ("IdState") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSAddresses"
    ADD FOREIGN KEY ("IDCity")
    REFERENCES public."PSCities" ("IdCIty") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSUserContactInfo"
    ADD FOREIGN KEY ("IDUser")
    REFERENCES public."PSUsers" ("IdUser") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSUserContactInfo"
    ADD FOREIGN KEY ("IdContactInfoType")
    REFERENCES public."PSContactInfoType" ("IdContactInfoType") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSPermissionsPerRole"
    ADD FOREIGN KEY ("PSRoles_IdRole")
    REFERENCES public."PSRoles" ("IdRole") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSPermissionsPerRole"
    ADD FOREIGN KEY ("PSPermissions_IdPermission")
    REFERENCES public."PSPermissions" ("IdPermission") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSRolesPerUser"
    ADD FOREIGN KEY ("PSUsers_IdUser")
    REFERENCES public."PSUsers" ("IdUser") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSRolesPerUser"
    ADD FOREIGN KEY ("PSRoles_IdRole")
    REFERENCES public."PSRoles" ("IdRole") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSLogs"
    ADD FOREIGN KEY ("IdLogType")
    REFERENCES public."PSLogTypes" ("IdLogType") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSLogs"
    ADD FOREIGN KEY ("IdLogLevel")
    REFERENCES public."PSLogLevels" ("IdLogLevel") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSLogs"
    ADD FOREIGN KEY ("IdLogSource")
    REFERENCES public."PSLogSources" ("IdLogSource") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSUsersXOrganization"
    ADD FOREIGN KEY ("PSOrganizations_IdOrganization")
    REFERENCES public."PSOrganizations" ("IdOrganization") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSUsersXOrganization"
    ADD FOREIGN KEY ("PSUsers_IdUser")
    REFERENCES public."PSUsers" ("IdUser") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCurrencies"
    ADD FOREIGN KEY ("IdCountry")
    REFERENCES public."PSCountries" ("IdCountry") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSExchangeRates"
    ADD FOREIGN KEY ("IdCurrencyDestiny")
    REFERENCES public."PSCurrencies" ("IdCurrency") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSExchangeRates"
    ADD FOREIGN KEY ("IdCurrencySource")
    REFERENCES public."PSCurrencies" ("IdCurrency") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSPayments"
    ADD FOREIGN KEY ("IdPaymentType")
    REFERENCES public."PSPaymentTypes" ("IdPaymentType") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSPayments"
    ADD FOREIGN KEY ("IdPaymentStatus")
    REFERENCES public."PSPaymentStatus" ("IdPaymentStatus") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSPayments"
    ADD FOREIGN KEY ("IdPaymentMethod")
    REFERENCES public."PSPaymentMethods" ("IdPaymentMethod") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSPayments"
    ADD FOREIGN KEY ("IdUser")
    REFERENCES public."PSUsers" ("IdUser") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSFeaturesPerSuscription"
    ADD FOREIGN KEY ("PSSubscriptions_IdSubscription")
    REFERENCES public."PSSubscriptions" ("IdSubscription") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSFeaturesPerSuscription"
    ADD FOREIGN KEY ("PSFeatures_IdFeature")
    REFERENCES public."PSFeatures" ("IdFeature") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSSubscriptionsPerUser"
    ADD FOREIGN KEY ("PSSubscriptions_IdSubscription")
    REFERENCES public."PSSubscriptions" ("IdSubscription") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSSubscriptionsPerUser"
    ADD FOREIGN KEY ("PSUsers_IdUser")
    REFERENCES public."PSUsers" ("IdUser") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaigns"
    ADD FOREIGN KEY ("IdOrganization")
    REFERENCES public."PSOrganizations" ("IdOrganization") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaigns"
    ADD FOREIGN KEY ("IdCurrency")
    REFERENCES public."PSCurrencies" ("IdCurrency") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaigns"
    ADD FOREIGN KEY ("IdCampaignStatus")
    REFERENCES public."PSCampaignStatus" ("IdCampaignStatus") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaigns"
    ADD FOREIGN KEY ("IdService")
    REFERENCES public."PSServices" ("IdService") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaigns"
    ADD FOREIGN KEY ("IdControl")
    REFERENCES public."PSETLControl" ("IdControl") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaignMetrics"
    ADD FOREIGN KEY ("IdCampaign")
    REFERENCES public."PSCampaigns" ("IdCampaign") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaignChannels"
    ADD FOREIGN KEY ("IdCampaign")
    REFERENCES public."PSCampaigns" ("IdCampaign") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSCampaingMarkets"
    ADD FOREIGN KEY ("IdCampaign")
    REFERENCES public."PSCampaigns" ("IdCampaign") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSLeadsSumarry"
    ADD FOREIGN KEY ("IdCampaign")
    REFERENCES public."PSCampaigns" ("IdCampaign") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSSalesSumarry"
    ADD FOREIGN KEY ("IdCampaign")
    REFERENCES public."PSCampaigns" ("IdCampaign") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSSalesSumarry"
    ADD FOREIGN KEY ("IdCurrency")
    REFERENCES public."PSCurrencies" ("IdCurrency") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSContentUsage"
    ADD FOREIGN KEY ("IdCampaign")
    REFERENCES public."PSCampaigns" ("IdCampaign") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSETLSources"
    ADD FOREIGN KEY ("IdSourceType")
    REFERENCES public."PSETLSourceTypes" ("IdSourceType") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSETLControl"
    ADD FOREIGN KEY ("IdSource")
    REFERENCES public."PSETLSources" ("IdSource") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSETLControl"
    ADD FOREIGN KEY ("IdServiceConnection")
    REFERENCES public."PSServiceConnections" ("IdServiceConnection") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSETLErrors"
    ADD FOREIGN KEY ("IdControl")
    REFERENCES public."PSETLControl" ("IdControl") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSETLDataSync"
    ADD FOREIGN KEY ("IdSource")
    REFERENCES public."PSETLSources" ("IdSource") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSAPISetups"
    ADD FOREIGN KEY ("IdAuthMethod")
    REFERENCES public."PSAuthMethods" ("IdAuthMethod") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSMCPServers"
    ADD FOREIGN KEY ("IdAuthMethod")
    REFERENCES public."PSAuthMethods" ("IdAuthMethod") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSAPICallLogs"
    ADD FOREIGN KEY ("IdAPISetup")
    REFERENCES public."PSAPISetups" ("IdAPISetup") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSAPICallLogs"
    ADD FOREIGN KEY ("IdControl")
    REFERENCES public."PSETLControl" ("IdControl") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSMCPRequestLogs"
    ADD FOREIGN KEY ("IdMCPServer")
    REFERENCES public."PSMCPServers" ("IdMCPServer") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSMCPRequestLogs"
    ADD FOREIGN KEY ("IdControl")
    REFERENCES public."PSETLControl" ("IdControl") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSServices"
    ADD FOREIGN KEY ("IdServiceType")
    REFERENCES public."PSServiceTypes" ("IdServiceType") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSServiceConnections"
    ADD FOREIGN KEY ("IdSourceService")
    REFERENCES public."PSServices" ("IdService") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSServiceConnections"
    ADD FOREIGN KEY ("IdTargetService")
    REFERENCES public."PSServices" ("IdService") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSServiceConnections"
    ADD FOREIGN KEY ("IdAPISetup")
    REFERENCES public."PSAPISetups" ("IdAPISetup") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PSServiceConnections"
    ADD FOREIGN KEY ("IdMCPServer")
    REFERENCES public."PSMCPServers" ("IdMCPServer") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;