-- Verificamos que todas tengan el identity que seria como el autoincrement

SELECT 
    tc.table_name,
    kcu.column_name,
    c.is_identity,
    c.column_default
FROM 
    information_schema.table_constraints tc
JOIN 
    information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name 
    AND tc.table_schema = kcu.table_schema
JOIN
    information_schema.columns c
    ON c.table_name = tc.table_name
    AND c.column_name = kcu.column_name
    AND c.table_schema = tc.table_schema
WHERE 
    tc.constraint_type = 'PRIMARY KEY'
    AND tc.table_schema = 'public'
ORDER BY 
    tc.table_name, kcu.ordinal_position;

ALTER TABLE public."PSLogs" ALTER COLUMN "IdLogType" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public."PSLogs" ALTER COLUMN "IdLogLevel" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public."PSLogs" ALTER COLUMN "IdLogSource" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public."PSPayments" ALTER COLUMN "IdPaymentType" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public."PSPayments" ALTER COLUMN "IdPaymentStatus" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public."PSPayments" ALTER COLUMN "IdPaymentMethod" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."PSServices" ALTER COLUMN "IdPaymentMethod" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."PSLeadsSumarry" ALTER COLUMN "IdLeadSumarry" ADD GENERATED BY DEFAULT AS IDENTITY;

