postgresql:
  service_name: localhost:30432
  database: promptsales
  username: postgres
  password: postgres123
  namespace: promptsales

mongodb:
  service_name: localhost:30017
  database: promptcontent
  namespace: promptcontent

sqlserver:
  service_name: localhost:31433
  database: promptads
  username: sa
  password: YourStrong!Passw0rd
  namespace: promptads

sqlserver2:
  service_name: localhost:32433
  database: promptcrm
  username: sa
  password: YourStrong!Passw0rd
  namespace: promptcrm
